version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: github.com/urfave/cli/v2
    versions:
    - 2.3.0
  - dependency-name: k8s.io/release
    versions:
    - 0.7.0
