---
version: 2.1

stdenv: &stdenv
  environment:
    GOCACHE: &gocache /home/circleci/.cache/go-build
    WORKDIR: &workdir /home/circleci/go/src/github.com/saschagrunert/go-modiff

executors:
  container:
    docker:
      - image: cimg/go:1.21
        user: circleci
    <<: *stdenv
    working_directory: *workdir

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - build-static
      - docs
      - lint
      - test
      - vendor

jobs:
  build:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-build-{{ checksum "go.sum" }}
      - run: go version
      - run:
          name: build
          command: make
      - save_cache:
          key: v2-build-{{ checksum "go.sum" }}
          paths:
            - build/go-modiff
            - *gocache
      - store_artifacts:
          path: build
          destination: bin

  build-static:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-build-static-{{ checksum "go.sum" }}
      - run: go version
      - run:
          name: build
          command: |
            make build/go-modiff.static
      - save_cache:
          key: v2-build-static-{{ checksum "go.sum" }}
          paths:
            - build/go-modiff
            - *gocache
      - store_artifacts:
          path: build
          destination: bin

  docs:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-docs-{{ checksum "go.sum" }}
      - run:
          name: docs
          command: |
            make docs
            .circleci/git-status
      - save_cache:
          key: v2-docs-{{ checksum "go.sum" }}
          paths:
            - build/go-modiff
            - *gocache
      - store_artifacts:
          path: docs
          destination: docs

  lint:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-golangci-lint-{{ checksum "go.sum" }}
      - run:
          name: lint
          command: make lint
      - save_cache:
          key: v2-golangci-lint-{{ checksum "go.sum" }}
          paths:
            - *gocache

  test:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-test-{{ checksum "go.sum" }}
      - run:
          name: test
          command: make test
      - run:
          name: code coverage
          command: make codecov
      - store_test_results:
          path: build/coverage
      - save_cache:
          key: v2-test-{{ checksum "go.sum" }}
          paths:
            - *gocache
            - build/ginkgo

  vendor:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-vendor-{{ checksum "go.sum" }}
      - run:
          name: check vendoring
          command: |
            make vendor
            .circleci/git-status
      - save_cache:
          key: v2-vendor-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg
