.nh
.TH go\-modiff 8

.SH NAME
.PP
go\-modiff \- Command line tool for diffing go module dependency changes between versions


.SH SYNOPSIS
.PP
go\-modiff

.PP
.RS

.nf
[\-\-debug|\-d]
[\-\-from|\-f]=[value]
[\-\-help|\-h]
[\-\-link|\-l]
[\-\-repository|\-r]=[value]
[\-\-to|\-t]=[value]
[\-\-version|\-v]

.fi
.RE


.SH DESCRIPTION
.PP
Command line tool for diffing go module dependency changes between versions

.PP
\fBUsage\fP:

.PP
.RS

.nf
go\-modiff [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-debug, \-d\fP: enable debug output

.PP
\fB\-\-from, \-f\fP="": the start of the comparison, any valid git rev (default: master)

.PP
\fB\-\-help, \-h\fP: show help

.PP
\fB\-\-link, \-l\fP: add diff links to the markdown output

.PP
\fB\-\-repository, \-r\fP="": repository to be used, like: github.com/owner/repo

.PP
\fB\-\-to, \-t\fP="": the end of the comparison, any valid git rev (default: master)

.PP
\fB\-\-version, \-v\fP: print the version


.SH COMMANDS
.SH docs, d
.PP
generate the markdown or man page documentation and print it to stdout

.PP
\fB\-\-help, \-h\fP: show help

.PP
\fB\-\-man\fP: print the man version

.PP
\fB\-\-markdown\fP: print the markdown version

.SH fish, f
.PP
generate the fish shell completion

.SH help, h
.PP
Shows a list of commands or help for one command

